In [1]:
import pandas as pd
from datetime import datetime, timedelta
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
"""Load training data from Excel file with multiple sheets"""
file_path = "./Phase 1 Training Dataset.xlsx"
xl = pd.ExcelFile(file_path)
groups = xl.sheet_names
train_df = pd.DataFrame()
test_df = pd.DataFrame()
for sheet in groups:
    df = pd.read_excel(file_path, sheet_name=sheet)
    
    # Skip the first row which contains staff type labels
    df = df.iloc[1:]
    
    # Convert the date column to datetime
    df['Date'] = pd.to_datetime(df.iloc[:, 0])
    
    # Sort by date to ensure temporal order
    df = df.sort_values('Date')
    
    # Calculate split point (80% train, 20% test)
    split_idx = int(len(df) * 0.8)
    
    for i in range(5):  # 5 NHs per group
        start_col = i * 4  # Each NH has 4 columns (NH No., CNA, LPN, RN)
        if start_col + 3 >= len(df.columns):
            break
            
        # Extract data for each staff type
        cna_data = pd.to_numeric(df.iloc[:, start_col + 1], errors='coerce')
        lpn_data = pd.to_numeric(df.iloc[:, start_col + 2], errors='coerce')
        rn_data = pd.to_numeric(df.iloc[:, start_col + 3], errors='coerce')        

        num_rows = len(df['Date'])
        # Add the columns in long format to the train and test dataframes
        aux_df_cna =  pd.DataFrame({
            'unique_id': [f"{sheet} NH No. {i + 1} CNA" for _ in range(num_rows)],
            'ds': df['Date'].dropna().tolist(),
            'y': cna_data.dropna().tolist()
        })
        aux_df_lpn =  pd.DataFrame({
            'unique_id': [f"{sheet} NH No. {i + 1} LPN" for _ in range(num_rows)],
            'ds': df['Date'].dropna().tolist(),
            'y': lpn_data.dropna().tolist()
        })
        aux_df_rn = pd.DataFrame({
            'unique_id': [f"{sheet} NH No. {i + 1} RN" for _ in range(num_rows)],
            'ds': df['Date'].dropna().tolist(),
            'y': rn_data.dropna().tolist()
        })
        train_df = pd.concat([train_df, aux_df_cna[:split_idx], aux_df_lpn[:split_idx], aux_df_rn[:split_idx]], ignore_index=True)
        test_df = pd.concat([test_df, aux_df_cna[split_idx:], aux_df_lpn[split_idx:], aux_df_rn[split_idx:]], ignore_index=True)

In [3]:
"""Training the model"""
import logging

import torch
from neuralforecast.core import NeuralForecast
from neuralforecast.models import TSMixer, NBEATS, NHITS, TFT
from neuralforecast.losses.pytorch import MAE, MAPE

logging.getLogger('pytorch_lightning').setLevel(logging.ERROR)
torch.set_float32_matmul_precision('high')

2025-02-25 10:41:23,065	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
2025-02-25 10:41:23,716	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

In [4]:
Y_df = pd.concat([train_df, test_df], ignore_index=True)
display(Y_df)
# We make validation and test splits
n_time = len(Y_df.ds.unique())
val_size = int(.2 * n_time)
test_size = int(.2 * n_time)
print(len(Y_df.unique_id.unique()))
print(val_size)

                  unique_id         ds       y
0      Group 1 NH No. 1 CNA 2024-04-01   87.72
1      Group 1 NH No. 1 CNA 2024-04-02   82.48
2      Group 1 NH No. 1 CNA 2024-04-03   78.47
3      Group 1 NH No. 1 CNA 2024-04-04   93.75
4      Group 1 NH No. 1 CNA 2024-04-05  103.25
...                     ...        ...     ...
27295  Group 20 NH No. 5 RN 2024-06-26   12.14
27296  Group 20 NH No. 5 RN 2024-06-27    0.00
27297  Group 20 NH No. 5 RN 2024-06-28   12.75
27298  Group 20 NH No. 5 RN 2024-06-29    8.00
27299  Group 20 NH No. 5 RN 2024-06-30    8.00

[27300 rows x 3 columns]

300
18

In [5]:
horizon = 7
input_size = 28
models = [
          # TSMixer(h=horizon,
          #       input_size=input_size,
          #       n_series=300,
          #       max_steps=1000,
          #       val_check_steps=100,
          #       early_stop_patience_steps=5,
          #       scaler_type='identity',
          #       valid_loss=MAE(),
          #       random_seed=12345678,
          #       ),
           NHITS(h=horizon,
                input_size=horizon,
                max_steps=1000,
                val_check_steps=10,
                early_stop_patience_steps=5,
                scaler_type='robust',
                valid_loss=MAE(),
                random_seed=12345678,
                ), 
           # NBEATS(h=horizon,
           #      input_size=horizon,
           #      max_steps=1000,
           #      val_check_steps=100,
           #      early_stop_patience_steps=5,
           #      scaler_type='robust',
           #      valid_loss=MAE(),
           #      random_seed=12345678,
           #      ), 
          # TFT(h=horizon,
          #       input_size=input_size,
          #       batch_size=5,
          #       max_steps=1000,
          #       val_check_steps=100,
          #       early_stop_patience_steps=5,
          #       scaler_type='identity',
          #       valid_loss=MAE(),
          #       random_seed=12345678,
          #       )   
         ]

Seed set to 12345678

In [6]:
nf = NeuralForecast(
    models=models,
    freq='D',
)

Y_hat_df = nf.cross_validation(
    df=Y_df,
    val_size=val_size,
    test_size=test_size,
    n_windows=None
)

Epoch 0: 100%|███████████████████████████████████████| 10/10 [00:02<00:00,  4.56it/s, v_num=174, train_loss_step=2.010]
Validation: |                                                                                    | 0/? [00:00<?, ?it/s]
Validation:   0%|                                                                               | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|                                                                  | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:  10%|█████▊                                                    | 1/10 [00:00<00:00, 31.98it/s]
Validation DataLoader 0:  20%|███████████▌                                              | 2/10 [00:00<00:00, 31.02it/s]
Validation DataLoader 0:  30%|█████████████████▍                                        | 3/10 [00:00<00:00, 36.15it/s]
Validation DataLoader 0:  40%|███████████████████████▏                                  | 4/10 [00:00<00:00, 34.41it/s]
Validation DataLoader 0:  50%|█████████████████████████████                             | 5/10 [00:00<00:00, 32.58it/s]
Validation DataLoader 0:  60%|██████████████████████████████████▊                       | 6/10 [00:00<00:00, 33.02it/s]
Validation DataLoader 0:  70%|████████████████████████████████████████▌                 | 7/10 [00:00<00:00, 32.62it/s]
Validation DataLoader 0:  80%|██████████████████████████████████████████████▍           | 8/10 [00:00<00:00, 33.05it/s]
Validation DataLoader 0:  90%|████████████████████████████████████████████████████▏     | 9/10 [00:00<00:00, 33.73it/s]
Validation DataLoader 0: 100%|█████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 35.33it/s]
Epoch 1: 100%|█| 10/10 [00:02<00:00,  4.62it/s, v_num=174, train_loss_step=2.440, valid_loss=10.30, train_loss_epoch=2.
Validation: |                                                                                    | 0/? [00:00<?, ?it/s]
Validation:   0%|                                                                               | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|                                                                  | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:  10%|█████▊                                                    | 1/10 [00:00<00:00, 31.14it/s]
Validation DataLoader 0:  20%|███████████▌                                              | 2/10 [00:00<00:00, 28.47it/s]
Validation DataLoader 0:  30%|█████████████████▍                                        | 3/10 [00:00<00:00, 29.86it/s]
Validation DataLoader 0:  40%|███████████████████████▏                                  | 4/10 [00:00<00:00, 29.89it/s]
Validation DataLoader 0:  50%|█████████████████████████████                             | 5/10 [00:00<00:00, 32.98it/s]
Validation DataLoader 0:  60%|██████████████████████████████████▊                       | 6/10 [00:00<00:00, 32.67it/s]
Validation DataLoader 0:  70%|████████████████████████████████████████▌                 | 7/10 [00:00<00:00, 32.24it/s]
Validation DataLoader 0:  80%|██████████████████████████████████████████████▍           | 8/10 [00:00<00:00, 31.95it/s]
Validation DataLoader 0:  90%|████████████████████████████████████████████████████▏     | 9/10 [00:00<00:00, 31.68it/s]
Validation DataLoader 0: 100%|█████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 32.81it/s]
Epoch 2: 100%|█| 10/10 [00:02<00:00,  4.47it/s, v_num=174, train_loss_step=2.210, valid_loss=10.10, train_loss_epoch=2.
Validation: |                                                                                    | 0/? [00:00<?, ?it/s]
Validation:   0%|                                                                               | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|                                                                  | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:  10%|█████▊                                                    | 1/10 [00:00<00:00, 22.45it/s]
Validation DataLoader 0:  20%|███████████▌                                              | 2/10 [00:00<00:00, 25.07it/s]
Validation DataLoader 0:  30%|█████████████████▍                                        | 3/10 [00:00<00:00, 26.97it/s]
Validation DataLoader 0:  40%|███████████████████████▏                                  | 4/10 [00:00<00:00, 30.11it/s]
Validation DataLoader 0:  50%|█████████████████████████████                             | 5/10 [00:00<00:00, 29.67it/s]
Validation DataLoader 0:  60%|██████████████████████████████████▊                       | 6/10 [00:00<00:00, 30.03it/s]
Validation DataLoader 0:  70%|████████████████████████████████████████▌                 | 7/10 [00:00<00:00, 30.25it/s]
Validation DataLoader 0:  80%|██████████████████████████████████████████████▍           | 8/10 [00:00<00:00, 30.60it/s]
Validation DataLoader 0:  90%|████████████████████████████████████████████████████▏     | 9/10 [00:00<00:00, 30.43it/s]
Validation DataLoader 0: 100%|█████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 32.11it/s]
Epoch 3: 100%|█| 10/10 [00:02<00:00,  4.64it/s, v_num=174, train_loss_step=3.170, valid_loss=9.990, train_loss_epoch=2.
Validation: |                                                                                    | 0/? [00:00<?, ?it/s]
Validation:   0%|                                                                               | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|                                                                  | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:  10%|█████▊                                                    | 1/10 [00:00<00:00, 49.25it/s]
Validation DataLoader 0:  20%|███████████▌                                              | 2/10 [00:00<00:00, 36.89it/s]
Validation DataLoader 0:  30%|█████████████████▍                                        | 3/10 [00:00<00:00, 34.73it/s]
Validation DataLoader 0:  40%|███████████████████████▏                                  | 4/10 [00:00<00:00, 33.95it/s]
Validation DataLoader 0:  50%|█████████████████████████████                             | 5/10 [00:00<00:00, 36.45it/s]
Validation DataLoader 0:  60%|██████████████████████████████████▊                       | 6/10 [00:00<00:00, 36.12it/s]
Validation DataLoader 0:  70%|████████████████████████████████████████▌                 | 7/10 [00:00<00:00, 34.19it/s]
Validation DataLoader 0:  80%|██████████████████████████████████████████████▍           | 8/10 [00:00<00:00, 34.40it/s]
Validation DataLoader 0:  90%|████████████████████████████████████████████████████▏     | 9/10 [00:00<00:00, 33.97it/s]
Validation DataLoader 0: 100%|█████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 35.27it/s]
Epoch 4: 100%|█| 10/10 [00:01<00:00,  5.05it/s, v_num=174, train_loss_step=2.740, valid_loss=9.970, train_loss_epoch=2.
Validation: |                                                                                    | 0/? [00:00<?, ?it/s]
Validation:   0%|                                                                               | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|                                                                  | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:  10%|█████▊                                                    | 1/10 [00:00<00:00, 30.99it/s]
Validation DataLoader 0:  20%|███████████▌                                              | 2/10 [00:00<00:00, 39.94it/s]
Validation DataLoader 0:  30%|█████████████████▍                                        | 3/10 [00:00<00:00, 36.47it/s]
Validation DataLoader 0:  40%|███████████████████████▏                                  | 4/10 [00:00<00:00, 34.58it/s]
Validation DataLoader 0:  50%|█████████████████████████████                             | 5/10 [00:00<00:00, 37.13it/s]
Validation DataLoader 0:  60%|██████████████████████████████████▊                       | 6/10 [00:00<00:00, 35.74it/s]
Validation DataLoader 0:  70%|████████████████████████████████████████▌                 | 7/10 [00:00<00:00, 38.10it/s]
Validation DataLoader 0:  80%|██████████████████████████████████████████████▍           | 8/10 [00:00<00:00, 35.95it/s]
Validation DataLoader 0:  90%|████████████████████████████████████████████████████▏     | 9/10 [00:00<00:00, 35.02it/s]
Validation DataLoader 0: 100%|█████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 32.85it/s]
Epoch 5: 100%|█| 10/10 [00:02<00:00,  4.99it/s, v_num=174, train_loss_step=1.820, valid_loss=10.00, train_loss_epoch=2.
Validation: |                                                                                    | 0/? [00:00<?, ?it/s]
Validation:   0%|                                                                               | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|                                                                  | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:  10%|█████▊                                                    | 1/10 [00:00<00:00, 27.35it/s]
Validation DataLoader 0:  20%|███████████▌                                              | 2/10 [00:00<00:00, 28.84it/s]
Validation DataLoader 0:  30%|█████████████████▍                                        | 3/10 [00:00<00:00, 30.60it/s]
Validation DataLoader 0:  40%|███████████████████████▏                                  | 4/10 [00:00<00:00, 34.30it/s]
Validation DataLoader 0:  50%|█████████████████████████████                             | 5/10 [00:00<00:00, 33.49it/s]
Validation DataLoader 0:  60%|██████████████████████████████████▊                       | 6/10 [00:00<00:00, 36.02it/s]
Validation DataLoader 0:  70%|████████████████████████████████████████▌                 | 7/10 [00:00<00:00, 35.00it/s]
Validation DataLoader 0:  80%|██████████████████████████████████████████████▍           | 8/10 [00:00<00:00, 34.24it/s]
Validation DataLoader 0:  90%|████████████████████████████████████████████████████▏     | 9/10 [00:00<00:00, 33.90it/s]
Validation DataLoader 0: 100%|█████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 34.89it/s]
Epoch 6: 100%|█| 10/10 [00:02<00:00,  4.78it/s, v_num=174, train_loss_step=2.200, valid_loss=9.940, train_loss_epoch=2.
Validation: |                                                                                    | 0/? [00:00<?, ?it/s]
Validation:   0%|                                                                               | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|                                                                  | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:  10%|█████▊                                                    | 1/10 [00:00<00:00, 31.70it/s]
Validation DataLoader 0:  20%|███████████▌                                              | 2/10 [00:00<00:00, 40.06it/s]
Validation DataLoader 0:  30%|█████████████████▍                                        | 3/10 [00:00<00:00, 35.20it/s]
Validation DataLoader 0:  40%|███████████████████████▏                                  | 4/10 [00:00<00:00, 33.81it/s]
Validation DataLoader 0:  50%|█████████████████████████████                             | 5/10 [00:00<00:00, 33.54it/s]
Validation DataLoader 0:  60%|██████████████████████████████████▊                       | 6/10 [00:00<00:00, 32.49it/s]
Validation DataLoader 0:  70%|████████████████████████████████████████▌                 | 7/10 [00:00<00:00, 32.37it/s]
Validation DataLoader 0:  80%|██████████████████████████████████████████████▍           | 8/10 [00:00<00:00, 32.68it/s]
Validation DataLoader 0:  90%|████████████████████████████████████████████████████▏     | 9/10 [00:00<00:00, 33.69it/s]
Validation DataLoader 0: 100%|█████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 35.26it/s]
Epoch 7: 100%|█| 10/10 [00:02<00:00,  4.61it/s, v_num=174, train_loss_step=1.980, valid_loss=9.940, train_loss_epoch=2.
Validation: |                                                                                    | 0/? [00:00<?, ?it/s]
Validation:   0%|                                                                               | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|                                                                  | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:  10%|█████▊                                                    | 1/10 [00:00<00:00, 29.69it/s]
Validation DataLoader 0:  20%|███████████▌                                              | 2/10 [00:00<00:00, 33.61it/s]
Validation DataLoader 0:  30%|█████████████████▍                                        | 3/10 [00:00<00:00, 31.91it/s]
Validation DataLoader 0:  40%|███████████████████████▏                                  | 4/10 [00:00<00:00, 31.30it/s]
Validation DataLoader 0:  50%|█████████████████████████████                             | 5/10 [00:00<00:00, 31.54it/s]
Validation DataLoader 0:  60%|██████████████████████████████████▊                       | 6/10 [00:00<00:00, 32.01it/s]
Validation DataLoader 0:  70%|████████████████████████████████████████▌                 | 7/10 [00:00<00:00, 33.24it/s]
Validation DataLoader 0:  80%|██████████████████████████████████████████████▍           | 8/10 [00:00<00:00, 32.94it/s]
Validation DataLoader 0:  90%|████████████████████████████████████████████████████▏     | 9/10 [00:00<00:00, 32.37it/s]
Validation DataLoader 0: 100%|█████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 32.83it/s]
Epoch 8: 100%|█| 10/10 [00:02<00:00,  4.57it/s, v_num=174, train_loss_step=2.040, valid_loss=9.970, train_loss_epoch=2.
Validation: |                                                                                    | 0/? [00:00<?, ?it/s]
Validation:   0%|                                                                               | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|                                                                  | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:  10%|█████▊                                                    | 1/10 [00:00<00:00, 28.91it/s]
Validation DataLoader 0:  20%|███████████▌                                              | 2/10 [00:00<00:00, 38.17it/s]
Validation DataLoader 0:  30%|█████████████████▍                                        | 3/10 [00:00<00:00, 30.79it/s]
Validation DataLoader 0:  40%|███████████████████████▏                                  | 4/10 [00:00<00:00, 33.59it/s]
Validation DataLoader 0:  50%|█████████████████████████████                             | 5/10 [00:00<00:00, 32.68it/s]
Validation DataLoader 0:  60%|██████████████████████████████████▊                       | 6/10 [00:00<00:00, 29.71it/s]
Validation DataLoader 0:  70%|████████████████████████████████████████▌                 | 7/10 [00:00<00:00, 28.32it/s]
Validation DataLoader 0:  80%|██████████████████████████████████████████████▍           | 8/10 [00:00<00:00, 27.47it/s]
Validation DataLoader 0:  90%|████████████████████████████████████████████████████▏     | 9/10 [00:00<00:00, 27.22it/s]
Validation DataLoader 0: 100%|█████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 28.33it/s]
Epoch 9: 100%|█| 10/10 [00:02<00:00,  4.44it/s, v_num=174, train_loss_step=2.650, valid_loss=9.910, train_loss_epoch=2.
Validation: |                                                                                    | 0/? [00:00<?, ?it/s]
Validation:   0%|                                                                               | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|                                                                  | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:  10%|█████▊                                                    | 1/10 [00:00<00:00, 30.03it/s]
Validation DataLoader 0:  20%|███████████▌                                              | 2/10 [00:00<00:00, 40.72it/s]
Validation DataLoader 0:  30%|█████████████████▍                                        | 3/10 [00:00<00:00, 36.41it/s]
Validation DataLoader 0:  40%|███████████████████████▏                                  | 4/10 [00:00<00:00, 34.55it/s]
Validation DataLoader 0:  50%|█████████████████████████████                             | 5/10 [00:00<00:00, 33.53it/s]
Validation DataLoader 0:  60%|██████████████████████████████████▊                       | 6/10 [00:00<00:00, 30.60it/s]
Validation DataLoader 0:  70%|████████████████████████████████████████▌                 | 7/10 [00:00<00:00, 29.82it/s]
Validation DataLoader 0:  80%|██████████████████████████████████████████████▍           | 8/10 [00:00<00:00, 29.44it/s]
Validation DataLoader 0:  90%|████████████████████████████████████████████████████▏     | 9/10 [00:00<00:00, 28.87it/s]
Validation DataLoader 0: 100%|█████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 29.72it/s]
Epoch 10: 100%|█| 10/10 [00:02<00:00,  4.75it/s, v_num=174, train_loss_step=1.660, valid_loss=9.920, train_loss_epoch=2
Validation: |                                                                                    | 0/? [00:00<?, ?it/s]
Validation:   0%|                                                                               | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|                                                                  | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:  10%|█████▊                                                    | 1/10 [00:00<00:00, 29.30it/s]
Validation DataLoader 0:  20%|███████████▌                                              | 2/10 [00:00<00:00, 29.83it/s]
Validation DataLoader 0:  30%|█████████████████▍                                        | 3/10 [00:00<00:00, 30.36it/s]
Validation DataLoader 0:  40%|███████████████████████▏                                  | 4/10 [00:00<00:00, 34.23it/s]
Validation DataLoader 0:  50%|█████████████████████████████                             | 5/10 [00:00<00:00, 32.89it/s]
Validation DataLoader 0:  60%|██████████████████████████████████▊                       | 6/10 [00:00<00:00, 32.88it/s]
Validation DataLoader 0:  70%|████████████████████████████████████████▌                 | 7/10 [00:00<00:00, 31.96it/s]
Validation DataLoader 0:  80%|██████████████████████████████████████████████▍           | 8/10 [00:00<00:00, 31.84it/s]
Validation DataLoader 0:  90%|████████████████████████████████████████████████████▏     | 9/10 [00:00<00:00, 31.40it/s]
Validation DataLoader 0: 100%|█████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 32.78it/s]
Epoch 11: 100%|█| 10/10 [00:02<00:00,  4.53it/s, v_num=174, train_loss_step=2.250, valid_loss=10.10, train_loss_epoch=2
Validation: |                                                                                    | 0/? [00:00<?, ?it/s]
Validation:   0%|                                                                               | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|                                                                  | 0/10 [00:00<?, ?it/s]
Validation DataLoader 0:  10%|█████▊                                                    | 1/10 [00:00<00:00, 30.08it/s]
Validation DataLoader 0:  20%|███████████▌                                              | 2/10 [00:00<00:00, 40.33it/s]
Validation DataLoader 0:  30%|█████████████████▍                                        | 3/10 [00:00<00:00, 36.00it/s]
Validation DataLoader 0:  40%|███████████████████████▏                                  | 4/10 [00:00<00:00, 34.21it/s]
Validation DataLoader 0:  50%|█████████████████████████████                             | 5/10 [00:00<00:00, 33.76it/s]
Validation DataLoader 0:  60%|██████████████████████████████████▊                       | 6/10 [00:00<00:00, 32.47it/s]
Validation DataLoader 0:  70%|████████████████████████████████████████▌                 | 7/10 [00:00<00:00, 32.70it/s]
Validation DataLoader 0:  80%|██████████████████████████████████████████████▍           | 8/10 [00:00<00:00, 34.27it/s]

In [7]:
Y_hat_df

                  unique_id         ds     cutoff       NHITS       y
0      Group 1 NH No. 1 CNA 2024-06-13 2024-06-12  106.875443   72.95
1      Group 1 NH No. 1 CNA 2024-06-14 2024-06-12   96.249535   98.54
2      Group 1 NH No. 1 CNA 2024-06-15 2024-06-12  101.849541  102.97
3      Group 1 NH No. 1 CNA 2024-06-16 2024-06-12   98.803345   85.11
4      Group 1 NH No. 1 CNA 2024-06-17 2024-06-12  100.624146   91.60
...                     ...        ...        ...         ...     ...
25195   Group 9 NH No. 5 RN 2024-06-26 2024-06-23   29.567356   55.50
25196   Group 9 NH No. 5 RN 2024-06-27 2024-06-23   32.880497   52.74
25197   Group 9 NH No. 5 RN 2024-06-28 2024-06-23   30.991808   27.37
25198   Group 9 NH No. 5 RN 2024-06-29 2024-06-23   28.199728   63.69
25199   Group 9 NH No. 5 RN 2024-06-30 2024-06-23   33.714363   57.88

[25200 rows x 5 columns]

In [8]:
from utilsforecast.evaluation import evaluate
from utilsforecast.losses import mae, mape

evaluate(Y_hat_df.drop(columns='cutoff'), metrics=[mae, mape], agg_fn='mean')

  metric      NHITS
0    mae  10.129242
1   mape   0.377335

In [9]:
Y_hat_insample = nf.predict_insample(step_size=1)
display(Y_hat_insample)

Predicting DataLoader 0: 100%|█████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  7.50it/s]

                   unique_id         ds     cutoff      NHITS           y
0       Group 1 NH No. 1 CNA 2024-04-01 2024-03-31  -0.071767   87.720001
1       Group 1 NH No. 1 CNA 2024-04-02 2024-03-31  -0.049857   82.480003
2       Group 1 NH No. 1 CNA 2024-04-03 2024-03-31  -0.067341   78.470001
3       Group 1 NH No. 1 CNA 2024-04-04 2024-03-31  -0.154967   93.750000
4       Group 1 NH No. 1 CNA 2024-04-05 2024-03-31  -0.216715  103.250000
...                      ...        ...        ...        ...         ...
140695   Group 9 NH No. 5 RN 2024-06-08 2024-06-05  31.061743   21.360001
140696   Group 9 NH No. 5 RN 2024-06-09 2024-06-05  30.896162   25.719999
140697   Group 9 NH No. 5 RN 2024-06-10 2024-06-05  27.609764   40.599998
140698   Group 9 NH No. 5 RN 2024-06-11 2024-06-05  23.541420   31.580000
140699   Group 9 NH No. 5 RN 2024-06-12 2024-06-05  24.588505   18.950001

[140700 rows x 5 columns]

In [10]:
Y_hat_agg = Y_hat_df.groupby(['unique_id', 'ds'], as_index=False).agg({
    'NHITS': 'mean',  # Mean of the NHITS column
    'y': 'first'  # Take the first value of 'y'
})
display(Y_hat_agg)
Y_hat_agg_insample = Y_hat_insample.groupby(['unique_id', 'ds'], as_index=False).agg({
    'NHITS': 'mean',  # Mean of the NHITS column
    'y': 'first'  # Take the first value of 'y'
})
display(Y_hat_agg_insample)

                 unique_id         ds       NHITS       y
0     Group 1 NH No. 1 CNA 2024-06-13  106.875443   72.95
1     Group 1 NH No. 1 CNA 2024-06-14   91.022079   98.54
2     Group 1 NH No. 1 CNA 2024-06-15   99.185768  102.97
3     Group 1 NH No. 1 CNA 2024-06-16   95.605179   85.11
4     Group 1 NH No. 1 CNA 2024-06-17   94.425377   91.60
...                    ...        ...         ...     ...
5395   Group 9 NH No. 5 RN 2024-06-26   29.739557   55.50
5396   Group 9 NH No. 5 RN 2024-06-27   32.687092   52.74
5397   Group 9 NH No. 5 RN 2024-06-28   30.707041   27.37
5398   Group 9 NH No. 5 RN 2024-06-29   28.194546   63.69
5399   Group 9 NH No. 5 RN 2024-06-30   33.714363   57.88

[5400 rows x 4 columns]

                  unique_id         ds      NHITS           y
0      Group 1 NH No. 1 CNA 2024-04-01  -0.071767   87.720001
1      Group 1 NH No. 1 CNA 2024-04-02  23.126263   82.480003
2      Group 1 NH No. 1 CNA 2024-04-03  34.602047   78.470001
3      Group 1 NH No. 1 CNA 2024-04-04  45.010357   93.750000
4      Group 1 NH No. 1 CNA 2024-04-05  54.114708  103.250000
...                     ...        ...        ...         ...
21895   Group 9 NH No. 5 RN 2024-06-08  30.133905   21.360001
21896   Group 9 NH No. 5 RN 2024-06-09  29.483833   25.719999
21897   Group 9 NH No. 5 RN 2024-06-10  27.016554   40.599998
21898   Group 9 NH No. 5 RN 2024-06-11  23.671944   31.580000
21899   Group 9 NH No. 5 RN 2024-06-12  24.588505   18.950001

[21900 rows x 4 columns]

In [11]:
Y_hat_final = pd.concat([Y_hat_agg_insample, Y_hat_agg], ignore_index=True)
Y_hat_final = Y_hat_final.groupby(['unique_id', 'ds'], as_index=False).mean() 

# Group by 'unique_id'
grouped = Y_hat_final.groupby('unique_id')

# Create a dictionary to store the separate DataFrames
df_dict = {unique_id: group for unique_id, group in grouped}

# Now, df_dict will contain each DataFrame for every unique 'unique_id'

# Iterate through each DataFrame in the dictionary
for unique_id, group in df_dict.items():
    # Replace the first 12 rows of the 'NHITS' column with the 'y' column
    group.iloc[:12, group.columns.get_loc('NHITS')] = group.iloc[:12]['y'].values
    group = group.reset_index(drop=True)
    # After modification, update the DataFrame in the dictionary
    df_dict[unique_id] = group
print(df_dict)

{'Group 1 NH No. 1 CNA':                unique_id         ds       NHITS           y
0   Group 1 NH No. 1 CNA 2024-04-01   87.720001   87.720001
1   Group 1 NH No. 1 CNA 2024-04-02   82.480003   82.480003
2   Group 1 NH No. 1 CNA 2024-04-03   78.470001   78.470001
3   Group 1 NH No. 1 CNA 2024-04-04   93.750000   93.750000
4   Group 1 NH No. 1 CNA 2024-04-05  103.250000  103.250000
..                   ...        ...         ...         ...
86  Group 1 NH No. 1 CNA 2024-06-26   94.061272  101.130000
87  Group 1 NH No. 1 CNA 2024-06-27   96.946037  107.000000
88  Group 1 NH No. 1 CNA 2024-06-28   97.129761  120.750000
89  Group 1 NH No. 1 CNA 2024-06-29   95.895157   95.250000
90  Group 1 NH No. 1 CNA 2024-06-30   92.750755   75.250000

[91 rows x 4 columns], 'Group 1 NH No. 1 LPN':                unique_id         ds      NHITS          y
0   Group 1 NH No. 1 LPN 2024-04-01  57.750000  57.750000
1   Group 1 NH No. 1 LPN 2024-04-02  66.750000  66.750000
2   Group 1 NH No. 1 LPN 2024-04-03  73.150002  73.150002
3   Group 1 NH No. 1 LPN 2024-04-04  83.089996  83.089996
4   Group 1 NH No. 1 LPN 2024-04-05  63.599998  63.599998
..                   ...        ...        ...        ...
86  Group 1 NH No. 1 LPN 2024-06-26  58.371132  62.940000
87  Group 1 NH No. 1 LPN 2024-06-27  55.162720  63.000000
88  Group 1 NH No. 1 LPN 2024-06-28  47.021362  86.750000
89  Group 1 NH No. 1 LPN 2024-06-29  46.810150  70.330000
90  Group 1 NH No. 1 LPN 2024-06-30  51.261105  64.830000

[91 rows x 4 columns], 'Group 1 NH No. 1 RN':               unique_id         ds      NHITS      y
0   Group 1 NH No. 1 RN 2024-04-01  27.250000  27.25
1   Group 1 NH No. 1 RN 2024-04-02  28.750000  28.75
2   Group 1 NH No. 1 RN 2024-04-03  33.500000  33.50
3   Group 1 NH No. 1 RN 2024-04-04  31.420000  31.42
4   Group 1 NH No. 1 RN 2024-04-05  30.910000  30.91
..                  ...        ...        ...    ...
86  Group 1 NH No. 1 RN 2024-06-26  35.954323  29.50
87  Group 1 NH No. 1 RN 2024-06-27  34.363380  20.25
88  Group 1 NH No. 1 RN 2024-06-28  34.403339  24.75
89  Group 1 NH No. 1 RN 2024-06-29  21.496197  20.50
90  Group 1 NH No. 1 RN 2024-06-30  23.199198  12.13

[91 rows x 4 columns], 'Group 1 NH No. 2 CNA':                unique_id         ds       NHITS           y
0   Group 1 NH No. 2 CNA 2024-04-01  166.899994  166.899994
1   Group 1 NH No. 2 CNA 2024-04-02  164.710007  164.710007
2   Group 1 NH No. 2 CNA 2024-04-03  175.279999  175.279999
3   Group 1 NH No. 2 CNA 2024-04-04  169.990005  169.990005
4   Group 1 NH No. 2 CNA 2024-04-05  165.809998  165.809998
..                   ...        ...         ...         ...
86  Group 1 NH No. 2 CNA 2024-06-26  158.489166  162.290000
87  Group 1 NH No. 2 CNA 2024-06-27  158.825150  156.360000
88  Group 1 NH No. 2 CNA 2024-06-28  157.658035  166.850000
89  Group 1 NH No. 2 CNA 2024-06-29  152.467255  154.600000
90  Group 1 NH No. 2 CNA 2024-06-30  151.240952  161.030000

[91 rows x 4 columns], 'Group 1 NH No. 2 LPN':                unique_id         ds      NHITS          y
0   Group 1 NH No. 2 LPN 2024-04-01  78.150002  78.150002
1   Group 1 NH No. 2 LPN 2024-04-02  92.349998  92.349998
2   Group 1 NH No. 2 LPN 2024-04-03  59.000000  59.000000
3   Group 1 NH No. 2 LPN 2024-04-04  63.310001  63.310001
4   Group 1 NH No. 2 LPN 2024-04-05  86.669998  86.669998
..                   ...        ...        ...        ...
86  Group 1 NH No. 2 LPN 2024-06-26  78.023727  59.930000
87  Group 1 NH No. 2 LPN 2024-06-27  78.521675  59.900000
88  Group 1 NH No. 2 LPN 2024-06-28  78.462471  68.550000
89  Group 1 NH No. 2 LPN 2024-06-29  71.479477  84.780000
90  Group 1 NH No. 2 LPN 2024-06-30  62.728516  77.780000

[91 rows x 4 columns], 'Group 1 NH No. 2 RN':               unique_id         ds      NHITS          y
0   Group 1 NH No. 2 RN 2024-04-01  30.900000  30.900000
1   Group 1 NH No. 2 RN 2024-04-02  18.129999  18.129999
2   Group 1 NH No. 2 RN 2024-04-03  34.290001  34.290001
3   Group 1 NH No. 2 RN 2024-04-04  36.470001  36.470001
4   Group 1 NH No. 2 RN 2024-04-05  24.000000  24.000000
..                  ...        ...        ...        ...
86  Group 1 NH No. 2 RN 2024-06-26  26.051380  36.070000
87  Group 1 NH No. 2 RN 2024-06-27  24.524843  37.500000
88  Group 1 NH No. 2 RN 2024-06-28  21.876730  24.500000
89  Group 1 NH No. 2 RN 2024-06-29  25.148041  12.390000
90  Group 1 NH No. 2 RN 2024-06-30  30.257330  18.080000

[91 rows x 4 columns], 'Group 1 NH No. 3 CNA':                unique_id         ds       NHITS           y
0   Group 1 NH No. 3 CNA 2024-04-01  138.750000  138.750000
1   Group 1 NH No. 3 CNA 2024-04-02  151.500000  151.500000
2   Group 1 NH No. 3 CNA 2024-04-03  124.500000  124.500000
3   Group 1 NH No. 3 CNA 2024-04-04  157.699997  157.699997
4   Group 1 NH No. 3 CNA 2024-04-05  127.000000  127.000000
..                   ...        ...         ...         ...
86  Group 1 NH No. 3 CNA 2024-06-26  137.488571  130.880000
87  Group 1 NH No. 3 CNA 2024-06-27  138.495117  130.600000
88  Group 1 NH No. 3 CNA 2024-06-28  138.519272  144.400000
89  Group 1 NH No. 3 CNA 2024-06-29  139.584839  132.630000
90  Group 1 NH No. 3 CNA 2024-06-30  139.241653  139.500000

[91 rows x 4 columns], 'Group 1 NH No. 3 LPN':                unique_id         ds       NHITS           y
0   Group 1 NH No. 3 LPN 2024-04-01  100.349998  100.349998
1   Group 1 NH No. 3 LPN 2024-04-02   87.769997   87.769997
2   Group 1 NH No. 3 LPN 2024-04-03   91.150002   91.150002
3   Group 1 NH No. 3 LPN 2024-04-04   75.699997   75.699997
4   Group 1 NH No. 3 LPN 2024-04-05   92.650002   92.650002
..                   ...        ...         ...         ...
86  Group 1 NH No. 3 LPN 2024-06-26   57.714100   57.750000
87  Group 1 NH No. 3 LPN 2024-06-27   56.146049   50.000000
88  Group 1 NH No. 3 LPN 2024-06-28   60.172226   69.800000
89  Group 1 NH No. 3 LPN 2024-06-29   53.271603   65.500000
90  Group 1 NH No. 3 LPN 2024-06-30   50.290596   71.000000

[91 rows x 4 columns], 'Group 1 NH No. 3 RN':               unique_id         ds      NHITS      y
0   Group 1 NH No. 3 RN 2024-04-01  18.000000  18.00
1   Group 1 NH No. 3 RN 2024-04-02  23.750000  23.75
2   Group 1 NH No. 3 RN 2024-04-03  22.250000  22.25
3   Group 1 NH No. 3 RN 2024-04-04  49.750000  49.75
4   Group 1 NH No. 3 RN 2024-04-05  41.250000  41.25
..                  ...        ...        ...    ...
86  Group 1 NH No. 3 RN 2024-06-26  37.310680  41.00
87  Group 1 NH No. 3 RN 2024-06-27  34.967407  62.25
88  Group 1 NH No. 3 RN 2024-06-28  35.696507  54.00
89  Group 1 NH No. 3 RN 2024-06-29  38.961662  18.50
90  Group 1 NH No. 3 RN 2024-06-30  39.361603  12.25

[91 rows x 4 columns], 'Group 1 NH No. 4 CNA':                unique_id         ds       NHITS           y
0   Group 1 NH No. 4 CNA 2024-04-01  120.370003  120.370003
1   Group 1 NH No. 4 CNA 2024-04-02  120.379997  120.379997
2   Group 1 NH No. 4 CNA 2024-04-03  118.120003  118.120003
3   Group 1 NH No. 4 CNA 2024-04-04  108.570000  108.570000
4   Group 1 NH No. 4 CNA 2024-04-05  113.419998  113.419998
..                   ...        ...         ...         ...
86  Group 1 NH No. 4 CNA 2024-06-26  103.440575  102.220000
87  Group 1 NH No. 4 CNA 2024-06-27  102.655441  107.930000
88  Group 1 NH No. 4 CNA 2024-06-28   99.425682   76.620000
89  Group 1 NH No. 4 CNA 2024-06-29  101.579605   73.650000
90  Group 1 NH No. 4 CNA 2024-06-30   97.577316   73.730000

[91 rows x 4 columns], 'Group 1 NH No. 4 LPN':                unique_id         ds      NHITS          y
0   Group 1 NH No. 4 LPN 2024-04-01  30.020000  30.020000
1   Group 1 NH No. 4 LPN 2024-04-02  34.139999  34.139999
2   Group 1 NH No. 4 LPN 2024-04-03  31.240000  31.240000
3   Group 1 NH No. 4 LPN 2024-04-04  23.059999  23.059999
4   Group 1 NH No. 4 LPN 2024-04-05  19.459999  19.459999
..                   ...        ...        ...        ...
86  Group 1 NH No. 4 LPN 2024-06-26  58.854042  62.140000
87  Group 1 NH No. 4 LPN 2024-06-27  56.839348  73.690000
88  Group 1 NH No. 4 LPN 2024-06-28  52.646439  37.280000
89  Group 1 NH No. 4 LPN 2024-06-29  56.988319  38.640000
90  Group 1 NH No. 4 LPN 2024-06-30  47.531708  43.150000

[91 rows x 4 columns], 'Group 1 NH No. 4 RN':               unique_id         ds      NHITS      y
0   Group 1 NH No. 4 RN 2024-04-01  20.670000  20.67
1   Group 1 NH No. 4 RN 2024-04-02  31.580000  31.58
2   Group 1 NH No. 4 RN 2024-04-03  27.430000  27.43
3   Group 1 NH No. 4 RN 2024-04-04  11.950000  11.95
4   Group 1 NH No. 4 RN 2024-04-05  32.730000  32.73
..                  ...        ...        ...    ...
86  Group 1 NH No. 4 RN 2024-06-26  11.134233   7.75
87  Group 1 NH No. 4 RN 2024-06-27  10.178196   9.47
88  Group 1 NH No. 4 RN 2024-06-28   8.699689   7.80
89  Group 1 NH No. 4 RN 2024-06-29  10.372182   9.58
90  Group 1 NH No. 4 RN 2024-06-30  11.401595  16.31

[91 rows x 4 columns], 'Group 1 NH No. 5 CNA':                unique_id         ds       NHITS       y
0   Group 1 NH No. 5 CNA 2024-04-01  204.000000  204.00
1   Group 1 NH No. 5 CNA 2024-04-02  250.000000  250.00
2   Group 1 NH No. 5 CNA 2024-04-03  232.750000  232.75
3   Group 1 NH No. 5 CNA 2024-04-04  236.750000  236.75
4   Group 1 NH No. 5 CNA 2024-04-05  211.000000  211.00
..                   ...        ...         ...     ...
86  Group 1 NH No. 5 CNA 2024-06-26  266.686920  255.75
87  Group 1 NH No. 5 CNA 2024-06-27  263.176239  261.00
88  Group 1 NH No. 5 CNA 2024-06-28  270.998199  293.75
89  Group 1 NH No. 5 CNA 2024-06-29  249.435699  247.00
90  Group 1 NH No. 5 CNA 2024-06-30  263.511230  266.00

[91 rows x 4 columns], 'Group 1 NH No. 5 LPN':                unique_id         ds       NHITS       y
0   Group 1 NH No. 5 LPN 2024-04-01  114.250000  114.25
1   Group 1 NH No. 5 LPN 2024-04-02  112.500000  112.50
2   Group 1 NH No. 5 LPN 2024-04-03  110.500000  110.50
3   Group 1 NH No. 5 LPN 2024-04-04   92.750000   92.75
4   Group 1 NH No. 5 LPN 2024-04-05   98.750000   98.75
..                   ...        ...         ...     ...
86  Group 1 NH No. 5 LPN 2024-06-26  104.733414  124.50
87  Group 1 NH No. 5 LPN 2024-06-27   99.465103  125.50
88  Group 1 NH No. 5 LPN 2024-06-28  101.408470  123.50
89  Group 1 NH No. 5 LPN 2024-06-29   93.010727   94.25
90  Group 1 NH No. 5 LPN 2024-06-30   98.840271  103.25

[91 rows x 4 columns], 'Group 1 NH No. 5 RN':               unique_id         ds      NHITS      y
0   Group 1 NH No. 5 RN 2024-04-01  39.750000  39.75
1   Group 1 NH No. 5 RN 2024-04-02  60.250000  60.25
2   Group 1 NH No. 5 RN 2024-04-03  50.000000  50.00
3   Group 1 NH No. 5 RN 2024-04-04  48.750000  48.75
4   Group 1 NH No. 5 RN 2024-04-05  64.250000  64.25
..                  ...        ...        ...    ...
86  Group 1 NH No. 5 RN 2024-06-26  29.348450  38.50
87  Group 1 NH No. 5 RN 2024-06-27  29.484245  34.50
88  Group 1 NH No. 5 RN 2024-06-28  27.837622  38.25
89  Group 1 NH No. 5 RN 2024-06-29  24.338036  22.00
90  Group 1 NH No. 5 RN 2024-06-30  23.108097   9.00

[91 rows x 4 columns], 'Group 10 NH No. 1 CNA':                 unique_id         ds       NHITS           y
0   Group 10 NH No. 1 CNA 2024-04-01  182.970001  182.970001
1   Group 10 NH No. 1 CNA 2024-04-02  228.800003  228.800003
2   Group 10 NH No. 1 CNA 2024-04-03  173.880005  173.880005
3   Group 10 NH No. 1 CNA 2024-04-04  182.059998  182.059998
4   Group 10 NH No. 1 CNA 2024-04-05  215.309998  215.309998
..                    ...        ...         ...         ...
86  Group 10 NH No. 1 CNA 2024-06-26  192.487289  193.550000
87  Group 10 NH No. 1 CNA 2024-06-27  188.799286  197.450000
88  Group 10 NH No. 1 CNA 2024-06-28  185.948746  181.750000
89  Group 10 NH No. 1 CNA 2024-06-29  184.216919  173.970000
90  Group 10 NH No. 1 CNA 2024-06-30  180.093933  152.930000

[91 rows x 4 columns], 'Group 10 NH No. 1 LPN':                 unique_id         ds      NHITS          y
0   Group 10 NH No. 1 LPN 2024-04-01  43.599998  43.599998
1   Group 10 NH No. 1 LPN 2024-04-02  46.500000  46.500000
2   Group 10 NH No. 1 LPN 2024-04-03  54.619999  54.619999
3   Group 10 NH No. 1 LPN 2024-04-04  83.860001  83.860001
4   Group 10 NH No. 1 LPN 2024-04-05  66.169998  66.169998
..                    ...        ...        ...        ...
86  Group 10 NH No. 1 LPN 2024-06-26  64.682175  61.810000
87  Group 10 NH No. 1 LPN 2024-06-27  65.478157  72.430000
88  Group 10 NH No. 1 LPN 2024-06-28  63.868256  65.230000
89  Group 10 NH No. 1 LPN 2024-06-29  67.489349  47.480000
90  Group 10 NH No. 1 LPN 2024-06-30  67.389954  45.330000

[91 rows x 4 columns], 'Group 10 NH No. 1 RN':                unique_id         ds      NHITS          y
0   Group 10 NH No. 1 RN 2024-04-01  46.509998  46.509998
1   Group 10 NH No. 1 RN 2024-04-02  46.270000  46.270000
2   Group 10 NH No. 1 RN 2024-04-03  36.480000  36.480000
3   Group 10 NH No. 1 RN 2024-04-04  20.459999  20.459999
4   Group 10 NH No. 1 RN 2024-04-05   9.880000   9.880000
..                   ...        ...        ...        ...
86  Group 10 NH No. 1 RN 2024-06-26  29.562622  39.610000
87  Group 10 NH No. 1 RN 2024-06-27  27.888000  25.950000
88  Group 10 NH No. 1 RN 2024-06-28  26.293951  27.200000
89  Group 10 NH No. 1 RN 2024-06-29  21.620255  14.150000
90  Group 10 NH No. 1 RN 2024-06-30  24.462963  41.520000

[91 rows x 4 columns], 'Group 10 NH No. 2 CNA':                 unique_id         ds       NHITS           y
0   Group 10 NH No. 2 CNA 2024-04-01  141.830002  141.830002
1   Group 10 NH No. 2 CNA 2024-04-02  143.500000  143.500000
2   Group 10 NH No. 2 CNA 2024-04-03  174.190002  174.190002
3   Group 10 NH No. 2 CNA 2024-04-04  167.199997  167.199997
4   Group 10 NH No. 2 CNA 2024-04-05  152.949997  152.949997
..                    ...        ...         ...         ...
86  Group 10 NH No. 2 CNA 2024-06-26  157.781235  148.700000
87  Group 10 NH No. 2 CNA 2024-06-27  154.599304  153.050000
88  Group 10 NH No. 2 CNA 2024-06-28  150.718842  148.050000
89  Group 10 NH No. 2 CNA 2024-06-29  141.693481  144.470000
90  Group 10 NH No. 2 CNA 2024-06-30  137.809174  135.250000

[91 rows x 4 columns], 'Group 10 NH No. 2 LPN':                 unique_id         ds      NHITS          y
0   Group 10 NH No. 2 LPN 2024-04-01  45.779999  45.779999
1   Group 10 NH No. 2 LPN 2024-04-02  35.990002  35.990002
2   Group 10 NH No. 2 LPN 2024-04-03  30.809999  30.809999
3   Group 10 NH No. 2 LPN 2024-04-04  34.779999  34.779999
4   Group 10 NH No. 2 LPN 2024-04-05  24.870001  24.870001
..                    ...        ...        ...        ...
86  Group 10 NH No. 2 LPN 2024-06-26  46.086712  55.170000
87  Group 10 NH No. 2 LPN 2024-06-27  43.861031  60.920000
88  Group 10 NH No. 2 LPN 2024-06-28  37.786041  24.560000
89  Group 10 NH No. 2 LPN 2024-06-29  34.133183  38.780000
90  Group 10 NH No. 2 LPN 2024-06-30  31.957027  31.890000

[91 rows x 4 columns], 'Group 10 NH No. 2 RN':                unique_id         ds      NHITS          y
0   Group 10 NH No. 2 RN 2024-04-01  24.799999  24.799999
1   Group 10 NH No. 2 RN 2024-04-02  29.719999  29.719999
2   Group 10 NH No. 2 RN 2024-04-03  16.530001  16.530001
3   Group 10 NH No. 2 RN 2024-04-04  13.600000  13.600000
4   Group 10 NH No. 2 RN 2024-04-05  39.830002  39.830002
..                   ...        ...        ...        ...
86  Group 10 NH No. 2 RN 2024-06-26  22.033964   7.250000
87  Group 10 NH No. 2 RN 2024-06-27  20.625969  16.320000
88  Group 10 NH No. 2 RN 2024-06-28  22.677034  32.710000
89  Group 10 NH No. 2 RN 2024-06-29  22.797449  24.600000
90  Group 10 NH No. 2 RN 2024-06-30  23.996063  31.650000

[91 rows x 4 columns], 'Group 10 NH No. 3 CNA':                 unique_id         ds       NHITS           y
0   Group 10 NH No. 3 CNA 2024-04-01  186.869995  186.869995
1   Group 10 NH No. 3 CNA 2024-04-02  197.860001  197.860001
2   Group 10 NH No. 3 CNA 2024-04-03  187.440002  187.440002
3   Group 10 NH No. 3 CNA 2024-04-04  190.429993  190.429993
4   Group 10 NH No. 3 CNA 2024-04-05  140.100006  140.100006
..                    ...        ...         ...         ...
86  Group 10 NH No. 3 CNA 2024-06-26  186.651611  219.680000
87  Group 10 NH No. 3 CNA 2024-06-27  186.325058  198.020000
88  Group 10 NH No. 3 CNA 2024-06-28  187.410477  194.180000
89  Group 10 NH No. 3 CNA 2024-06-29  188.743240  199.040000
90  Group 10 NH No. 3 CNA 2024-06-30  191.527451  181.620000

[91 rows x 4 columns], 'Group 10 NH No. 3 LPN':                 unique_id         ds      NHITS          y
0   Group 10 NH No. 3 LPN 2024-04-01  87.790001  87.790001
1   Group 10 NH No. 3 LPN 2024-04-02  89.529999  89.529999
2   Group 10 NH No. 3 LPN 2024-04-03  62.790001  62.790001
3   Group 10 NH No. 3 LPN 2024-04-04  70.129997  70.129997
4   Group 10 NH No. 3 LPN 2024-04-05  80.730003  80.730003
..                    ...        ...        ...        ...
86  Group 10 NH No. 3 LPN 2024-06-26  70.039902  79.940000
87  Group 10 NH No. 3 LPN 2024-06-27  64.720673  98.770000
88  Group 10 NH No. 3 LPN 2024-06-28  66.610603  81.770000
89  Group 10 NH No. 3 LPN 2024-06-29  58.479126  54.050000
90  Group 10 NH No. 3 LPN 2024-06-30  54.312355  59.480000

[91 rows x 4 columns], 'Group 10 NH No. 3 RN':                unique_id         ds      NHITS          y
0   Group 10 NH No. 3 RN 2024-04-01  30.469999  30.469999
1   Group 10 NH No. 3 RN 2024-04-02  23.860001  23.860001
2   Group 10 NH No. 3 RN 2024-04-03  50.590000  50.590000
3   Group 10 NH No. 3 RN 2024-04-04  49.919998  49.919998
4   Group 10 NH No. 3 RN 2024-04-05  33.730000  33.730000
..                   ...        ...        ...        ...
86  Group 10 NH No. 3 RN 2024-06-26  42.907921  43.490000
87  Group 10 NH No. 3 RN 2024-06-27  41.765667  27.050000
88  Group 10 NH No. 3 RN 2024-06-28  37.917103  36.380000
89  Group 10 NH No. 3 RN 2024-06-29  38.066872  39.030000
90  Group 10 NH No. 3 RN 2024-06-30  43.291943  42.500000

[91 rows x 4 columns], 'Group 10 NH No. 4 CNA':                 unique_id         ds       NHITS           y
0   Group 10 NH No. 4 CNA 2024-04-01  127.279999  127.279999
1   Group 10 NH No. 4 CNA 2024-04-02  121.010002  121.010002
2   Group 10 NH No. 4 CNA 2024-04-03  135.039993  135.039993
3   Group 10 NH No. 4 CNA 2024-04-04  132.660004  132.660004
4   Group 10 NH No. 4 CNA 2024-04-05  127.400002  127.400002
..                    ...        ...         ...         ...
86  Group 10 NH No. 4 CNA 2024-06-26  135.581131  143.040000
87  Group 10 NH No. 4 CNA 2024-06-27  131.132050  156.060000
88  Group 10 NH No. 4 CNA 2024-06-28  134.846298  143.000000
89  Group 10 NH No. 4 CNA 2024-06-29  132.933868  147.670000
90  Group 10 NH No. 4 CNA 2024-06-30  130.523697  142.730000

[91 rows x 4 columns], 'Group 10 NH No. 4 LPN':                 unique_id         ds      NHITS          y
0   Group 10 NH No. 4 LPN 2024-04-01  15.480000  15.480000
1   Group 10 NH No. 4 LPN 2024-04-02  25.309999  25.309999
2   Group 10 NH No. 4 LPN 2024-04-03  28.570000  28.570000
3   Group 10 NH No. 4 LPN 2024-04-04  24.030001  24.030001
4   Group 10 NH No. 4 LPN 2024-04-05  13.180000  13.180000
..                    ...        ...        ...        ...
86  Group 10 NH No. 4 LPN 2024-06-26  25.366901  22.500000
87  Group 10 NH No. 4 LPN 2024-06-27  24.425169  27.720000
88  Group 10 NH No. 4 LPN 2024-06-28  22.401945  24.890000
89  Group 10 NH No. 4 LPN 2024-06-29  21.878389   2.070000
90  Group 10 NH No. 4 LPN 2024-06-30  24.638401   6.100000

[91 rows x 4 columns], 'Group 10 NH No. 4 RN':                unique_id         ds      NHITS          y
0   Group 10 NH No. 4 RN 2024-04-01  24.360001  24.360001
1   Group 10 NH No. 4 RN 2024-04-02   9.030000   9.030000
2   Group 10 NH No. 4 RN 2024-04-03   9.300000   9.300000
3   Group 10 NH No. 4 RN 2024-04-04  11.130000  11.130000
4   Group 10 NH No. 4 RN 2024-04-05  12.180000  12.180000
..                   ...        ...        ...        ...
86  Group 10 NH No. 4 RN 2024-06-26  20.585821  24.580000
87  Group 10 NH No. 4 RN 2024-06-27  21.137146  16.300000
88  Group 10 NH No. 4 RN 2024-06-28  20.955698  24.720000

In [12]:
# Create a new dictionary to store DataFrames with keys containing both the group number and type of staff eg. "CNA"
joined_dfs_by_group = {} 
for i in range(20): # total groups
    for j in ["CNA", "LPN", "RN"]:
        joined_dfs_by_group[f"Group {i+1} " + j] = {key: df for key, df in df_dict.items() if f"Group {i+1} " in key and j in key}
# iterate through each dictionary containing the results for the same group and staff type, to join the 5 NH values in one dataframe for point estimate and interval calculation
wide_dfs_by_group = {} 
for name, grpstf in joined_dfs_by_group.items():
    # initialise empty DF
    wide_dfs_by_group[name] = pd.DataFrame()
    for k, v in grpstf.items():
        wide_dfs_by_group[name]["ds"] = v["ds"]
        # populate the dataframe with extra columns
        wide_dfs_by_group[name]["NHITS" + k] = v["NHITS"]
        wide_dfs_by_group[name]["y" + k] = v["y"]
    # Calculate the mean across the 5 columns for each row
    wide_dfs_by_group[name]['Mean'] = wide_dfs_by_group[name].filter(like='NHITS').mean(axis=1)
    # Calculate the standard deviation across the 'NHITS' columns
    wide_dfs_by_group[name]['Std'] = wide_dfs_by_group[name].filter(like='NHITS').std(axis=1)
    
    # Calculate the 95% confidence interval using Mean_NHITS as the point estimate
    # wide_dfs_by_group[name]['Lower_95%'] = wide_dfs_by_group[name]['Mean'] - 1.96 * wide_dfs_by_group[name]['Std']
    # wide_dfs_by_group[name]['Upper_95%'] = wide_dfs_by_group[name]['Mean'] + 1.96 * wide_dfs_by_group[name]['Std']
    # Calculate the 95% confidence interval (upper and lower bounds) across the 'NHITS' columns
    wide_dfs_by_group[name]['Lower_95%'] = wide_dfs_by_group[name].filter(like='NHITS').quantile(0.05, axis=1)
    wide_dfs_by_group[name]['Upper_95%'] = wide_dfs_by_group[name].filter(like='NHITS').quantile(0.95, axis=1)

print(wide_dfs_by_group['Group 1 CNA'])

           ds  NHITSGroup 1 NH No. 1 CNA  yGroup 1 NH No. 1 CNA  \
0  2024-04-01                  87.720001              87.720001
1  2024-04-02                  82.480003              82.480003
2  2024-04-03                  78.470001              78.470001
3  2024-04-04                  93.750000              93.750000
4  2024-04-05                 103.250000             103.250000
..        ...                        ...                    ...
86 2024-06-26                  94.061272             101.130000
87 2024-06-27                  96.946037             107.000000
88 2024-06-28                  97.129761             120.750000
89 2024-06-29                  95.895157              95.250000
90 2024-06-30                  92.750755              75.250000

    NHITSGroup 1 NH No. 2 CNA  yGroup 1 NH No. 2 CNA  \
0                  166.899994             166.899994
1                  164.710007             164.710007
2                  175.279999             175.279999
3                  169.990005             169.990005
4                  165.809998             165.809998
..                        ...                    ...
86                 158.489166             162.290000
87                 158.825150             156.360000
88                 157.658035             166.850000
89                 152.467255             154.600000
90                 151.240952             161.030000

    NHITSGroup 1 NH No. 3 CNA  yGroup 1 NH No. 3 CNA  \
0                  138.750000             138.750000
1                  151.500000             151.500000
2                  124.500000             124.500000
3                  157.699997             157.699997
4                  127.000000             127.000000
..                        ...                    ...
86                 137.488571             130.880000
87                 138.495117             130.600000
88                 138.519272             144.400000
89                 139.584839             132.630000
90                 139.241653             139.500000

    NHITSGroup 1 NH No. 4 CNA  yGroup 1 NH No. 4 CNA  \
0                  120.370003             120.370003
1                  120.379997             120.379997
2                  118.120003             118.120003
3                  108.570000             108.570000
4                  113.419998             113.419998
..                        ...                    ...
86                 103.440575             102.220000
87                 102.655441             107.930000
88                  99.425682              76.620000
89                 101.579605              73.650000
90                  97.577316              73.730000

    NHITSGroup 1 NH No. 5 CNA  yGroup 1 NH No. 5 CNA        Mean        Std  \
0                  204.000000                 204.00  143.548004  44.375572
1                  250.000000                 250.00  153.813995  62.414333
2                  232.750000                 232.75  145.824005  59.545300
3                  236.750000                 236.75  153.352005  56.587940
4                  211.000000                 211.00  144.095993  44.298222
..                        ...                    ...         ...        ...
86                 266.686920                 255.75  152.033295  69.138794
87                 263.176239                 261.00  152.019608  67.184341
88                 270.998199                 293.75  152.746185  70.968887
89                 249.435699                 247.00  147.792511  61.744484
90                 263.511230                 266.00  148.864380  68.958763

     Lower_95%   Upper_95%
0    94.250002  196.579999
1    90.060002  232.942001
2    86.400002  221.256000
3    96.714000  223.398001
4   105.284000  201.962000
..         ...         ...
86   95.937132  245.047369
87   98.087918  242.306021
88   97.588945  248.330167
89   97.032047  230.042010
90   93.716068  241.057175

[91 rows x 15 columns]

In [13]:
def create_prediction_template(output_file, groups):
    """Create predictions for all groups and save to template"""
    # Create Excel writer
    writer = pd.ExcelWriter(output_file, engine='openpyxl')
    df = pd.DataFrame()
    df["Date"] = wide_dfs_by_group['Group 1 CNA']['ds']
    # Create predictions for each group
    for group in groups:
        for staff_type in ['CNA', 'LPN', 'RN']:
            # Select the values corresponding to keys containing both "Group 1" and "CNA"
            for key, value in wide_dfs_by_group.items():
                if f"{group} " in key and staff_type in key:
                    df[f'{staff_type} Point Prediction'] = value["Mean"]
                    df[f'{staff_type} Lower Bound'] = value["Lower_95%"]
                    df[f'{staff_type} Upper Bound'] = value["Upper_95%"]
        
        # Create DataFrame and save to sheet
        df.to_excel(writer, sheet_name=group, index=False)
        
    writer.close()

# create_prediction_template("./Phase 1 Prediction Output.xlsx", groups)

SyntaxError: invalid syntax (2481093358.py, line 13)

In [26]:
def calculate_mae(y_true, y_pred):
    """Calculate Mean Absolute Error"""
    return np.mean(np.abs(y_true - y_pred))

def calculate_mape(y_true, y_pred):
    """Calculate Mean Absolute Percentage Error with handling for small values"""
    # Use a threshold to avoid division by very small numbers
    threshold = 1.0
    mask = y_true > threshold
    if not np.any(mask):
        return np.nan
    return 100 * np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask]))

def calculate_smape(y_true, y_pred):
    """Calculate Symmetric Mean Absolute Percentage Error"""
    return 100 * np.mean(2.0 * np.abs(y_pred - y_true) / (np.abs(y_true) + np.abs(y_pred)))

def calculate_mis(y_true, y_pred, lower_bound, upper_bound):
    """Calculate Mean Interval Score with robust handling of outliers"""
    alpha = 0.05
    n = len(y_true)
    
    # Initialize components of MIS
    coverage_penalty = np.zeros(n)
    width_penalty = np.zeros(n)
    
    # Calculate penalties with outlier-robust handling
    for i in range(n):
        interval_width = upper_bound[i] - lower_bound[i]
        
        if y_true[i] < lower_bound[i]:
            coverage_penalty[i] = 2/alpha * (lower_bound[i] - y_true[i])
        elif y_true[i] > upper_bound[i]:
            coverage_penalty[i] = 2/alpha * (y_true[i] - upper_bound[i])
            
        width_penalty[i] = interval_width
        
    # Use median instead of mean for more robustness
    mis = np.median(width_penalty + coverage_penalty)
    return mis

def evaluate_predictions(y_true, y_pred, lower_bound, upper_bound):
    """Evaluate predictions using all metrics"""
    metrics = {
        'MAE': calculate_mae(y_true, y_pred),
        'MAPE': calculate_mape(y_true, y_pred),
        'SMAPE': calculate_smape(y_true, y_pred),
        'MIS': calculate_mis(y_true, y_pred, lower_bound, upper_bound)
    }
    return metrics

def evaluate_all_data(groups):
    train_metrics = {
        'CNA': {'MAE': [], 'MAPE': [], 'SMAPE': [], 'MIS': []},
        'LPN': {'MAE': [], 'MAPE': [], 'SMAPE': [], 'MIS': []},
        'RN': {'MAE': [], 'MAPE': [], 'SMAPE': [], 'MIS': []}, 
    }
    test_metrics = {
        'CNA': {'MAE': [], 'MAPE': [], 'SMAPE': [], 'MIS': []},
        'LPN': {'MAE': [], 'MAPE': [], 'SMAPE': [], 'MIS': []},
        'RN': {'MAE': [], 'MAPE': [], 'SMAPE': [], 'MIS': []}
    }
    train_metrics_calcs = {
        'y_true_CNA': np.array([]),
        'y_pred_CNA': np.array([]),
        'lower_bound_CNA': np.array([]),
        'upper_bound_CNA': np.array([]),
        'y_true_LPN': np.array([]),
        'y_pred_LPN': np.array([]),
        'lower_bound_LPN': np.array([]),
        'upper_bound_LPN': np.array([]),
        'y_true_RN': np.array([]),
        'y_pred_RN': np.array([]),
        'lower_bound_RN': np.array([]),
        'upper_bound_RN': np.array([])
    }
    test_metrics_calcs = {
        'y_true_CNA': np.array([]),
        'y_pred_CNA': np.array([]),
        'lower_bound_CNA': np.array([]),
        'upper_bound_CNA': np.array([]),
        'y_true_LPN': np.array([]),
        'y_pred_LPN': np.array([]),
        'lower_bound_LPN': np.array([]),
        'upper_bound_LPN': np.array([]),
        'y_true_RN': np.array([]),
        'y_pred_RN': np.array([]),
        'lower_bound_RN': np.array([]),
        'upper_bound_RN': np.array([])
    }
    # Create the arrays for evaulation of each staff group using the metrics
    for group in groups:
        for staff_type in ['CNA', 'LPN', 'RN']:
            # Select the values corresponding to keys containing both "Group 1" and "CNA"
            for key, value in wide_dfs_by_group.items():
                if f"{group} " in key and staff_type in key:
                    # for training set (72 per group staff type, exclude the last 19 rows)
                    train_metrics_calcs[f'y_true_{staff_type}'] = np.concatenate((train_metrics_calcs[f'y_true_{staff_type}'], value[f'y{group} NH No. 1 {staff_type}'][:-19].to_numpy()))
                    train_metrics_calcs[f'y_pred_{staff_type}'] = np.concatenate((train_metrics_calcs[f'y_pred_{staff_type}'], value['Mean'][:-19].to_numpy()))
                    train_metrics_calcs[f'lower_bound_{staff_type}'] = np.concatenate((train_metrics_calcs[f'lower_bound_{staff_type}'], value['Lower_95%'][:-19].to_numpy()))
                    train_metrics_calcs[f'upper_bound_{staff_type}'] = np.concatenate((train_metrics_calcs[f'upper_bound_{staff_type}'], value['Upper_95%'][:-19].to_numpy()))
                    train_metrics_calcs[f'y_true_{staff_type}'] = np.concatenate((train_metrics_calcs[f'y_true_{staff_type}'], value[f'y{group} NH No. 2 {staff_type}'][:-19].to_numpy()))
                    train_metrics_calcs[f'y_pred_{staff_type}'] = np.concatenate((train_metrics_calcs[f'y_pred_{staff_type}'], value['Mean'][:-19].to_numpy()))
                    train_metrics_calcs[f'lower_bound_{staff_type}'] = np.concatenate((train_metrics_calcs[f'lower_bound_{staff_type}'], value['Lower_95%'][:-19].to_numpy()))
                    train_metrics_calcs[f'upper_bound_{staff_type}'] = np.concatenate((train_metrics_calcs[f'upper_bound_{staff_type}'], value['Upper_95%'][:-19].to_numpy()))
                    train_metrics_calcs[f'y_true_{staff_type}'] = np.concatenate((train_metrics_calcs[f'y_true_{staff_type}'], value[f'y{group} NH No. 3 {staff_type}'][:-19].to_numpy()))
                    train_metrics_calcs[f'y_pred_{staff_type}'] = np.concatenate((train_metrics_calcs[f'y_pred_{staff_type}'], value['Mean'][:-19].to_numpy()))
                    train_metrics_calcs[f'lower_bound_{staff_type}'] = np.concatenate((train_metrics_calcs[f'lower_bound_{staff_type}'], value['Lower_95%'][:-19].to_numpy()))
                    train_metrics_calcs[f'upper_bound_{staff_type}'] = np.concatenate((train_metrics_calcs[f'upper_bound_{staff_type}'], value['Upper_95%'][:-19].to_numpy()))
                    train_metrics_calcs[f'y_true_{staff_type}'] = np.concatenate((train_metrics_calcs[f'y_true_{staff_type}'], value[f'y{group} NH No. 4 {staff_type}'][:-19].to_numpy()))
                    train_metrics_calcs[f'y_pred_{staff_type}'] = np.concatenate((train_metrics_calcs[f'y_pred_{staff_type}'], value['Mean'][:-19].to_numpy()))
                    train_metrics_calcs[f'lower_bound_{staff_type}'] = np.concatenate((train_metrics_calcs[f'lower_bound_{staff_type}'], value['Lower_95%'][:-19].to_numpy()))
                    train_metrics_calcs[f'upper_bound_{staff_type}'] = np.concatenate((train_metrics_calcs[f'upper_bound_{staff_type}'], value['Upper_95%'][:-19].to_numpy()))
                    train_metrics_calcs[f'y_true_{staff_type}'] = np.concatenate((train_metrics_calcs[f'y_true_{staff_type}'], value[f'y{group} NH No. 5 {staff_type}'][:-19].to_numpy()))
                    train_metrics_calcs[f'y_pred_{staff_type}'] = np.concatenate((train_metrics_calcs[f'y_pred_{staff_type}'], value['Mean'][:-19].to_numpy()))
                    train_metrics_calcs[f'lower_bound_{staff_type}'] = np.concatenate((train_metrics_calcs[f'lower_bound_{staff_type}'], value['Lower_95%'][:-19].to_numpy()))
                    train_metrics_calcs[f'upper_bound_{staff_type}'] = np.concatenate((train_metrics_calcs[f'upper_bound_{staff_type}'], value['Upper_95%'][:-19].to_numpy()))

                    # for test set (19 per group staff type)
                    test_metrics_calcs[f'y_true_{staff_type}'] = np.concatenate((test_metrics_calcs[f'y_true_{staff_type}'], value[f'y{group} NH No. 1 {staff_type}'].tail(19).to_numpy()))
                    test_metrics_calcs[f'y_pred_{staff_type}'] = np.concatenate((test_metrics_calcs[f'y_pred_{staff_type}'], value['Mean'].tail(19).to_numpy()))
                    test_metrics_calcs[f'lower_bound_{staff_type}'] = np.concatenate((test_metrics_calcs[f'lower_bound_{staff_type}'], value['Lower_95%'].tail(19).to_numpy()))
                    test_metrics_calcs[f'upper_bound_{staff_type}'] = np.concatenate((test_metrics_calcs[f'upper_bound_{staff_type}'], value['Upper_95%'].tail(19).to_numpy()))
                    test_metrics_calcs[f'y_true_{staff_type}'] = np.concatenate((test_metrics_calcs[f'y_true_{staff_type}'], value[f'y{group} NH No. 2 {staff_type}'].tail(19).to_numpy()))
                    test_metrics_calcs[f'y_pred_{staff_type}'] = np.concatenate((test_metrics_calcs[f'y_pred_{staff_type}'], value['Mean'].tail(19).to_numpy()))
                    test_metrics_calcs[f'lower_bound_{staff_type}'] = np.concatenate((test_metrics_calcs[f'lower_bound_{staff_type}'], value['Lower_95%'].tail(19).to_numpy()))
                    test_metrics_calcs[f'upper_bound_{staff_type}'] = np.concatenate((test_metrics_calcs[f'upper_bound_{staff_type}'], value['Upper_95%'].tail(19).to_numpy()))
                    test_metrics_calcs[f'y_true_{staff_type}'] = np.concatenate((test_metrics_calcs[f'y_true_{staff_type}'], value[f'y{group} NH No. 3 {staff_type}'].tail(19).to_numpy()))
                    test_metrics_calcs[f'y_pred_{staff_type}'] = np.concatenate((test_metrics_calcs[f'y_pred_{staff_type}'], value['Mean'].tail(19).to_numpy()))
                    test_metrics_calcs[f'lower_bound_{staff_type}'] = np.concatenate((test_metrics_calcs[f'lower_bound_{staff_type}'], value['Lower_95%'].tail(19).to_numpy()))
                    test_metrics_calcs[f'upper_bound_{staff_type}'] = np.concatenate((test_metrics_calcs[f'upper_bound_{staff_type}'], value['Upper_95%'].tail(19).to_numpy()))
                    test_metrics_calcs[f'y_true_{staff_type}'] = np.concatenate((test_metrics_calcs[f'y_true_{staff_type}'], value[f'y{group} NH No. 4 {staff_type}'].tail(19).to_numpy()))
                    test_metrics_calcs[f'y_pred_{staff_type}'] = np.concatenate((test_metrics_calcs[f'y_pred_{staff_type}'], value['Mean'].tail(19).to_numpy()))
                    test_metrics_calcs[f'lower_bound_{staff_type}'] = np.concatenate((test_metrics_calcs[f'lower_bound_{staff_type}'], value['Lower_95%'].tail(19).to_numpy()))
                    test_metrics_calcs[f'upper_bound_{staff_type}'] = np.concatenate((test_metrics_calcs[f'upper_bound_{staff_type}'], value['Upper_95%'].tail(19).to_numpy()))
                    test_metrics_calcs[f'y_true_{staff_type}'] = np.concatenate((test_metrics_calcs[f'y_true_{staff_type}'], value[f'y{group} NH No. 5 {staff_type}'].tail(19).to_numpy()))
                    test_metrics_calcs[f'y_pred_{staff_type}'] = np.concatenate((test_metrics_calcs[f'y_pred_{staff_type}'], value['Mean'].tail(19).to_numpy()))
                    test_metrics_calcs[f'lower_bound_{staff_type}'] = np.concatenate((test_metrics_calcs[f'lower_bound_{staff_type}'], value['Lower_95%'].tail(19).to_numpy()))
                    test_metrics_calcs[f'upper_bound_{staff_type}'] = np.concatenate((test_metrics_calcs[f'upper_bound_{staff_type}'], value['Upper_95%'].tail(19).to_numpy()))

    for staff_type in ['CNA', 'LPN', 'RN']:
        #populate the training metrics
        y_true = train_metrics_calcs[f'y_true_{staff_type}']
        y_pred = train_metrics_calcs[f'y_pred_{staff_type}']
        lower_bound = train_metrics_calcs[f'lower_bound_{staff_type}']
        upper_bound = train_metrics_calcs[f'upper_bound_{staff_type}']
        train_metrics_results = evaluate_predictions(y_true, y_pred, lower_bound, upper_bound)
        train_metrics[f'{staff_type}']['MAE'] = train_metrics_results['MAE']
        train_metrics[f'{staff_type}']['MAPE'] = train_metrics_results['MAPE']
        train_metrics[f'{staff_type}']['SMAPE'] = train_metrics_results['SMAPE']
        train_metrics[f'{staff_type}']['MIS'] = train_metrics_results['MIS']
        # Populate the test metrics
        y_true = test_metrics_calcs[f'y_true_{staff_type}']
        y_pred = test_metrics_calcs[f'y_pred_{staff_type}']
        lower_bound = test_metrics_calcs[f'lower_bound_{staff_type}']
        upper_bound = test_metrics_calcs[f'upper_bound_{staff_type}']
        test_metrics_results = evaluate_predictions(y_true, y_pred, lower_bound, upper_bound)
        test_metrics[f'{staff_type}']['MAE'] = test_metrics_results['MAE']
        test_metrics[f'{staff_type}']['MAPE'] = test_metrics_results['MAPE']
        test_metrics[f'{staff_type}']['SMAPE'] = test_metrics_results['SMAPE']
        test_metrics[f'{staff_type}']['MIS'] = test_metrics_results['MIS']
    # Print training metrics
    print("\nTraining Set Metrics:")
    print("--------------------")
    for staff_type in ['CNA', 'LPN', 'RN']:
        print(f"\n{staff_type} Metrics:")
        print("-" * 20)
        for metric_name in ['MAE', 'MAPE', 'SMAPE', 'MIS']:
            values = train_metrics[staff_type][metric_name]
            avg_value = np.mean(values)
            print(f"{metric_name}: {avg_value:.2f}")
    
    # Print test metrics
    print("\nTest Set Metrics:")
    print("----------------")
    for staff_type in ['CNA', 'LPN', 'RN']:
        print(f"\n{staff_type} Metrics:")
        print("-" * 20)
        for metric_name in ['MAE', 'MAPE', 'SMAPE', 'MIS']:
            values = test_metrics[staff_type][metric_name]
            avg_value = np.mean(values)
            print(f"{metric_name}: {avg_value:.2f}")

In [27]:
evaluate_all_data(groups)

Training Set Metrics:
--------------------

CNA Metrics:
--------------------
MAE: 30.47
MAPE: 25.97
SMAPE: 21.88
MIS: 91.59

LPN Metrics:
--------------------
MAE: 17.90
MAPE: 49.91
SMAPE: 37.51
MIS: 61.68

RN Metrics:
--------------------
MAE: 15.38
MAPE: 66.83
SMAPE: 53.56
MIS: 52.41

Test Set Metrics:
----------------

CNA Metrics:
--------------------
MAE: 30.92
MAPE: 24.66
SMAPE: 21.86
MIS: 90.61

LPN Metrics:
--------------------
MAE: 17.57
MAPE: 52.40
SMAPE: 38.14
MIS: 51.73

RN Metrics:
--------------------
MAE: 15.81
MAPE: 68.91
SMAPE: 52.10
MIS: 53.30

In [ ]:
# from ray import tune
# from ray.tune.search.hyperopt import HyperOptSearch
# from neuralforecast.auto import AutoTSMixer

# tsmixer_config = {
#        "input_size": input_size,                                                 # Size of input window
#        "max_steps": tune.choice([500, 1000, 2000]),                              # Number of training iterations
#        "val_check_steps": 100,                                                   # Compute validation every x steps
#        "early_stop_patience_steps": 5,                                           # Early stopping steps
#        "learning_rate": tune.loguniform(1e-4, 1e-2),                             # Initial Learning rate
#        "n_block": tune.choice([1, 2, 4, 6, 8]),                                  # Number of mixing layers
#        "dropout": tune.uniform(0.0, 0.99),                                       # Dropout
#        "ff_dim": tune.choice([32, 64, 128]),                                     # Dimension of the feature linear layer
#        "scaler_type": 'identity',       
#     }

# tsmixerx_config = tsmixer_config.copy()

# model = AutoTSMixer(h=horizon,
#                     n_series=300,
#                     loss=MAE(),
#                     config=tsmixer_config,
#                     num_samples=10,
#                     search_alg=HyperOptSearch(),
#                     backend='ray',
#                     valid_loss=MAE())

# nf = NeuralForecast(models=[model], freq='1D')
# Y_hat_df = nf.cross_validation(df=Y_df, val_size=val_size,
#                                test_size=test_size, n_windows=None)

In [ ]:
# nf.models[0].results.get_best_result().config

In [ ]:
# evaluate(Y_hat_df.drop(columns='cutoff'), metrics=[mae, mape], agg_fn="mean")